/*
=========================================================================

                        WinSpoutDX.cpp - LSE Sender

   A Windows Desktop Application project generated by Visual Studio
   and adapted for Spout input (http://spout.zeal.co/).

   This example has been modified for use with the Live Stream Extension
   for Unreal Engine. This external application is meant to be used
   along-side LSE to provide a live webview2 texture to share with
   the engine.

=========================================================================

 * Copyright (C) 2024 Kaleb Knoettgen
 * All Rights Reserved.
 *
 * Unauthorized reproduction, modification, or distribution of this
 * software is prohibited. Provided "AS IS" without warranty; Kaleb
 * Knoettgen is not liable for any damages arising from its use.
 * All rights not expressly granted are reserved.
 *
 * For more information, visit: www.kalebknoettgen.com
 * Contact: kalebknoettgen@gmail.com

=========================================================================

                 Copyright(C) 2020-2024 Lynn Jarvis.

This program is free software : you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.If not, see < http://www.gnu.org/licenses/>.
========================================================================

*/

#include "WinSpoutDX.h"


int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
    _In_opt_ HINSTANCE hPrevInstance,
    _In_ LPWSTR    lpCmdLine,
    _In_ int       nCmdShow)
{
    UNREFERENCED_PARAMETER(hPrevInstance);

    // Initialize COM for WebView2 (STA)
    if (FAILED(CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED))) {
        MessageBox(nullptr, "Failed to initialize COM", "LSESender", MB_OK | MB_ICONERROR);
        return FALSE;
    }

    // --- parse command line for URL (argv[1]) and sender name (argv[2]) overrides ---
    int    argc = 0;
    LPWSTR* argv = CommandLineToArgvW(GetCommandLineW(), &argc);
    if (argv) {
        // 1st arg -> WebView2 URL
        if (argc > 1 && argv[1][0] != L'\0') {
            wv_initialUrl = argv[1];
        }
        // 2nd arg -> Spout sender name
        if (argc > 2 && argv[2][0] != L'\0') {
            // convert wide‐string to UTF-8
            int len = WideCharToMultiByte(CP_UTF8, 0, argv[2], -1, nullptr, 0, nullptr, nullptr);
            senderName.resize(len - 1);
            WideCharToMultiByte(CP_UTF8, 0, argv[2], -1, &senderName[0], len, nullptr, nullptr);
        }
        LocalFree(argv);
    }
    // ---------------------------------------------------

    MyRegisterClass(hInstance);

    // Perform application initialization:
    if (!InitInstance(hInstance, nCmdShow))
        return FALSE;

    // Determine initial client size for buffer
    RECT rcClient;
    GetClientRect(g_hWnd, &rcClient);
    g_SenderWidth = rcClient.right - rcClient.left;
    g_SenderHeight = rcClient.bottom - rcClient.top;
    g_pixelBuffer = new unsigned char[g_SenderWidth * g_SenderHeight * 4];

    // SPOUT: Initialize DirectX 11
    if (!sender.OpenDirectX11())
        return FALSE;
    // use the potentially overridden senderName
    sender.SetSenderName(senderName.c_str());

    // Create WebView2 environment and controller
    CreateCoreWebView2EnvironmentWithOptions(
        nullptr, nullptr, nullptr,
        Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
            [](HRESULT envResult, ICoreWebView2Environment* env) -> HRESULT {
                if (SUCCEEDED(envResult) && env) {
                    env->CreateCoreWebView2Controller(
                        g_hWnd,
                        Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                            [](HRESULT ctrlResult, ICoreWebView2Controller* controller) -> HRESULT {
                                if (SUCCEEDED(ctrlResult) && controller) {
                                    g_webviewController = controller;
                                    g_webviewController->get_CoreWebView2(&g_webViewWindow);
                                    RECT bounds;
                                    GetClientRect(g_hWnd, &bounds);
                                    g_webviewController->put_Bounds(bounds);
                                    g_webviewController->get_ParentWindow(&g_hWebView);
                                    // Use the (possibly overridden) URL here
                                    g_webViewWindow->Navigate(wv_initialUrl.c_str());
                                }
                                return S_OK;
                            }).Get());
                }
                return S_OK;
            }).Get());

    // Main message loop:
    MSG msg = { 0 };
    while (WM_QUIT != msg.message) {
        if (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE)) {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
        else {
            Render();
        }
    }

    // Clean up
    delete[] g_pixelBuffer;
    sender.ReleaseSender();
    sender.CloseDirectX11();
    CoUninitialize();

    return (int)msg.wParam;
}

//
//  FUNCTION: MyRegisterClass()
//
ATOM MyRegisterClass(HINSTANCE hInstance)
{
    WNDCLASSEXA wcex = { sizeof(WNDCLASSEX) };

    wcex.style = CS_HREDRAW | CS_VREDRAW;
    wcex.lpfnWndProc = WndProc;
    wcex.hInstance = hInstance;
    wcex.hIcon = LoadIcon(hInstance, MAKEINTRESOURCE(IDI_LSEICON));
    wcex.hIconSm = LoadIcon(hInstance, MAKEINTRESOURCE(IDI_LSEICON));
    wcex.hCursor = LoadCursor(nullptr, IDC_ARROW);
    wcex.hbrBackground = CreateHatchBrush(6, RGB(0, 0, 0));
    wcex.lpszClassName = windowClass;

    return RegisterClassExA(&wcex);
}

//
//   FUNCTION: InitInstance(HINSTANCE, int)
//
BOOL InitInstance(HINSTANCE hInstance, int nCmdShow)
{
    hInst = hInstance;

    RECT rc = { 0, 0, (LONG)g_SenderWidth, (LONG)g_SenderHeight };
    AdjustWindowRect(&rc, WS_POPUPWINDOW, TRUE);
    HWND hWnd = CreateWindowA(
        windowClass, senderName.c_str(),
        WS_POPUPWINDOW,
        CW_USEDEFAULT, CW_USEDEFAULT,
        rc.right - rc.left, rc.bottom - rc.top,
        nullptr, nullptr, hInstance, nullptr);

    if (!hWnd)
        return FALSE;

    // Move window completely off-screen
    RECT winRect;
    GetWindowRect(hWnd, &winRect);
    int width = winRect.right - winRect.left;
    int height = winRect.bottom - winRect.top;

    // e.g. push it just beyond the top-left corner
    int x = -width - 50;   // 50 pixels further offscreen
    int y = -height - 50;

    MoveWindow(hWnd, x, y, width, height, FALSE);


    ShowWindow(hWnd, nCmdShow);
    UpdateWindow(hWnd);

    g_hWnd = hWnd;
    return TRUE;
}

//
//  FUNCTION: Render()
//  PURPOSE:  Captures the WebView2 content into our pixel buffer and sends via Spout
//
void Render()
{
    InvalidateRect(g_hWnd, NULL, FALSE);
    UpdateWindow(g_hWnd);

    sender.spoutcopy.ClearAlpha(g_pixelBuffer, g_SenderWidth, g_SenderHeight, 255);
    sender.SendImage(g_pixelBuffer, g_SenderWidth, g_SenderHeight);
    sender.HoldFps(60);
}

//
//  FUNCTION: WndProc(...)
//
LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
    switch (message)
    {
    case WM_PAINT:
        if (!g_hWebView) break;
        {
            PAINTSTRUCT ps;
            HDC hdc = BeginPaint(hWnd, &ps);
            RECT rcClient; GetClientRect(hWnd, &rcClient);
            UINT width = rcClient.right - rcClient.left;
            UINT height = rcClient.bottom - rcClient.top;
            if (width != g_SenderWidth || height != g_SenderHeight) {
                g_SenderWidth = width; g_SenderHeight = height;
                delete[] g_pixelBuffer;
                g_pixelBuffer = new unsigned char[width * height * 4];
                g_webviewController->put_Bounds(rcClient);
            }
            HDC hdcMem = CreateCompatibleDC(hdc);
            HBITMAP hBmp = CreateCompatibleBitmap(hdc, width, height);
            HBITMAP hOld = (HBITMAP)SelectObject(hdcMem, hBmp);
            PrintWindow(g_hWebView, hdcMem, PW_RENDERFULLCONTENT);
            GetBitmapBits(hBmp, width * height * 4, g_pixelBuffer);
            SelectObject(hdcMem, hOld);
            DeleteObject(hBmp);
            DeleteDC(hdcMem);
            EndPaint(hWnd, &ps);
        }
        break;

    case WM_WINDOWPOSCHANGING:
    {
        WINDOWPOS* p = reinterpret_cast<WINDOWPOS*>(lParam);
        p->hwndInsertAfter = HWND_BOTTOM;
        p->flags |= SWP_NOACTIVATE;
    }
    break;

    case WM_DESTROY:
        PostQuitMessage(0);
        break;

    default:
        return DefWindowProc(hWnd, message, wParam, lParam);
    }
    return 0;
}
